### ISSUE TITLE
Packagist.org

### ISSUE THREAD

**Issue by razbakov** [TheExtensionLab/WidgetImage#1]
Hello, I added your module to https://packagist.org/packages/theextensionlab/widgetimage
Let me know your account, so I can transfer ownership back to you.

**Comment by JamesAnelay** [comment]
Hey @razbakov,
Cool - My account is:
e-mail:jamesanelay@theextensionlab.com
username:Theextensionlab

Thanks James

**Comment by razbakov** [comment]
Done
