### ISSUE TITLE
No Magento 1.9.3 compatibility

### ISSUE THREAD

**Issue by Lmbrtz** [TheExtensionLab/WidgetImage#2]
Hi there,

I have just tried to use your extension with Magento 1.9.3, but the image upload buttons are not showing (image browsing works though).
I tried it with Magento 1.9.2.4 and that works fine.

Just wanted to let you know. Maybe you can find a fix for it?

**Comment by JamesAnelay** [comment]
Thanks @MichaelFurtner will look into fixing early next week.

**Comment by JamesAnelay** [comment]
I'll not be fixing this, it's open for a pull request if somebody else wished to do so.
